### 讀取PM2.5數據TO MYSQL

In [8]:
import pandas as pd
import pymysql

In [11]:
api_url="https://data.moenv.gov.tw/api/v2/aqx_p_02?api_key=540e2ca4-41e1-4186-8497-fdd67024ac44&limit=1000&sort=datacreationdate%20desc&format=CSV"

In [13]:
df=pd.read_csv(api_url)
df

    site county  pm25  datacreationdate itemunit
0     員林    彰化縣  21.0  2025-04-23 18:00    μg/m3
1     大城    彰化縣  16.0  2025-04-23 18:00    μg/m3
2    富貴角    新北市  11.0  2025-04-23 18:00    μg/m3
3     麥寮    雲林縣  13.0  2025-04-23 18:00    μg/m3
4     關山    臺東縣  12.0  2025-04-23 18:00    μg/m3
..   ...    ...   ...               ...      ...
995   竹東    新竹縣  12.0  2025-04-23 06:00    μg/m3
996   湖口    新竹縣  10.0  2025-04-23 06:00    μg/m3
997   龍潭    桃園市   NaN  2025-04-23 06:00    μg/m3
998   平鎮    桃園市  15.0  2025-04-23 06:00    μg/m3
999   觀音    桃園市  21.0  2025-04-23 06:00    μg/m3

[1000 rows x 5 columns]

### 轉換時間格式刪除空值

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   site              1000 non-null   object
 1   county            1000 non-null   object
 2   pm25              970 non-null    float64
 3   datacreationdate  1000 non-null   object
 4   itemunit          1000 non-null   object
dtypes: float64(1), object(4)
memory usage: 39.2+ KB

In [17]:
df["datacreationdate"]=pd.to_datetime(df["datacreationdate"])
df

    site county  pm25    datacreationdate itemunit
0     員林    彰化縣  21.0 2025-04-23 18:00:00    μg/m3
1     大城    彰化縣  16.0 2025-04-23 18:00:00    μg/m3
2    富貴角    新北市  11.0 2025-04-23 18:00:00    μg/m3
3     麥寮    雲林縣  13.0 2025-04-23 18:00:00    μg/m3
4     關山    臺東縣  12.0 2025-04-23 18:00:00    μg/m3
..   ...    ...   ...                 ...      ...
995   竹東    新竹縣  12.0 2025-04-23 06:00:00    μg/m3
996   湖口    新竹縣  10.0 2025-04-23 06:00:00    μg/m3
997   龍潭    桃園市   NaN 2025-04-23 06:00:00    μg/m3
998   平鎮    桃園市  15.0 2025-04-23 06:00:00    μg/m3
999   觀音    桃園市  21.0 2025-04-23 06:00:00    μg/m3

[1000 rows x 5 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   site              1000 non-null   object
 1   county            1000 non-null   object
 2   pm25              970 non-null    float64
 3   datacreationdate  1000 non-null   datetime64[ns]
 4   itemunit          1000 non-null   object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 39.2+ KB

### isna()比對
- df.dropna()

In [27]:
df1=df.drop(df[df["pm25"].isna()].index)
df1

    site county  pm25    datacreationdate itemunit
0     員林    彰化縣  21.0 2025-04-23 18:00:00    μg/m3
1     大城    彰化縣  16.0 2025-04-23 18:00:00    μg/m3
2    富貴角    新北市  11.0 2025-04-23 18:00:00    μg/m3
3     麥寮    雲林縣  13.0 2025-04-23 18:00:00    μg/m3
4     關山    臺東縣  12.0 2025-04-23 18:00:00    μg/m3
..   ...    ...   ...                 ...      ...
994   新竹    新竹市  14.0 2025-04-23 06:00:00    μg/m3
995   竹東    新竹縣  12.0 2025-04-23 06:00:00    μg/m3
996   湖口    新竹縣  10.0 2025-04-23 06:00:00    μg/m3
998   平鎮    桃園市  15.0 2025-04-23 06:00:00    μg/m3
999   觀音    桃園市  21.0 2025-04-23 06:00:00    μg/m3

[970 rows x 5 columns]

### 最新時間資料

In [31]:
latest_time=df1["datacreationdate"].max()
latest_time

Timestamp('2025-04-23 18:00:00')

In [33]:
df1[df1["datacreationdate"]==latest_time]

   site county  pm25    datacreationdate itemunit
0    員林    彰化縣  21.0 2025-04-23 18:00:00    μg/m3
1    大城    彰化縣  16.0 2025-04-23 18:00:00    μg/m3
2   富貴角    新北市  11.0 2025-04-23 18:00:00    μg/m3
3    麥寮    雲林縣  13.0 2025-04-23 18:00:00    μg/m3
4    關山    臺東縣  12.0 2025-04-23 18:00:00    μg/m3
..  ...    ...   ...                 ...      ...
74   土城    新北市  22.0 2025-04-23 18:00:00    μg/m3
75   新店    新北市  20.0 2025-04-23 18:00:00    μg/m3
76   萬里    新北市  11.0 2025-04-23 18:00:00    μg/m3
77   汐止    新北市  19.0 2025-04-23 18:00:00    μg/m3
78   基隆    基隆市  11.0 2025-04-23 18:00:00    μg/m3

[76 rows x 5 columns]

### 找出臺北市所有站點平均PM2.5值

In [35]:
df1["county"].unique()

array(['彰化縣', '新北市', '雲林縣', '臺東縣', '澎湖縣', '連江縣', '南投縣', '高雄市', '桃園市',
       '宜蘭縣', '臺北市', '花蓮縣', '屏東縣', '臺南市', '嘉義市', '嘉義縣', '臺中市', '苗栗縣',
       '新竹市', '新竹縣', '基隆市'], dtype=object)

In [40]:
df1.groupby("county").get_group("臺北市").groupby("site")["pm25"].mean()

site
中山    11.583333
古亭     9.583333
士林     8.333333
大同    15.083333
松山    16.916667
萬華     8.416667
陽明     3.769231
Name: pm25, dtype: float64

In [43]:
taipei=df1[df1["county"]=="臺北市"]
taipei

    site county  pm25    datacreationdate itemunit
16    陽明    臺北市   1.0 2025-04-23 18:00:00    μg/m3
63    大同    臺北市  20.0 2025-04-23 18:00:00    μg/m3
64    松山    臺北市  68.0 2025-04-23 18:00:00    μg/m3
65    古亭    臺北市  17.0 2025-04-23 18:00:00    μg/m3
66    萬華    臺北市  16.0 2025-04-23 18:00:00    μg/m3
..   ...    ...   ...                 ...      ...
926   古亭    臺北市  15.0 2025-04-23 07:00:00    μg/m3
927   萬華    臺北市  12.0 2025-04-23 07:00:00    μg/m3
928   中山    臺北市  16.0 2025-04-23 07:00:00    μg/m3
929   士林    臺北市  15.0 2025-04-23 07:00:00    μg/m3
955   陽明    臺北市  11.0 2025-04-23 06:00:00    μg/m3

[85 rows x 5 columns]

In [47]:
taipei.groupby("site")["pm25"].mean()

site
中山    11.583333
古亭     9.583333
士林     8.333333
大同    15.083333
松山    16.916667
萬華     8.416667
陽明     3.769231
Name: pm25, dtype: float64

### 寫入資料庫(mysql)